sudo: required

services: 
  - docker

before_install: 
  - docker build -t anmolsrivastava/react-test -f ./client/Dockerfile.dev ./client


script: 
  - docker run -e CI=true anmolsrivastava/react-test npm test

after_success: 
  - docker build anmolsrivastava/multi-client ./client
  - docker build anmolsrivastava/multi-nginx ./nginx
  - docker build anmolsrivastava/multi-server ./server
  - docker build anmolsrivastava/multi-worker ./worker